<?php

namespace Database\Seeders\GenesisMomentum;

use Illuminate\Database\Seeder;

class NomContractMethodsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('nom_contract_methods')->delete();

        \DB::table('nom_contract_methods')->insert([
            0 => [
                'id' => 1,
                'contract_id' => 1,
                'name' => 'CreateProject',
                'signature' => 'CreateProject(string,string,string,uint256,uint256)',
                'fingerprint' => '77c044b6',
            ],
            1 => [
                'id' => 2,
                'contract_id' => 1,
                'name' => 'AddPhase',
                'signature' => 'AddPhase(hash,string,string,string,uint256,uint256)',
                'fingerprint' => 'c7e13ddc',
            ],
            2 => [
                'id' => 3,
                'contract_id' => 1,
                'name' => 'UpdatePhase',
                'signature' => 'UpdatePhase(hash,string,string,string,uint256,uint256)',
                'fingerprint' => 'c1d7d323',
            ],
            3 => [
                'id' => 4,
                'contract_id' => 1,
                'name' => 'Donate',
                'signature' => 'Donate()',
                'fingerprint' => 'cb7f8b2a',
            ],
            4 => [
                'id' => 5,
                'contract_id' => 1,
                'name' => 'VoteByName',
                'signature' => 'VoteByName(hash,string,uint8)',
                'fingerprint' => '5c6c1064',
            ],
            5 => [
                'id' => 6,
                'contract_id' => 1,
                'name' => 'VoteByProdAddress',
                'signature' => 'VoteByProdAddress(hash,uint8)',
                'fingerprint' => '90ed001c',
            ],
            6 => [
                'id' => 7,
                'contract_id' => 2,
                'name' => 'WrapToken',
                'signature' => 'WrapToken(uint32,uint32,string)',
                'fingerprint' => '61d224bc',
            ],
            7 => [
                'id' => 8,
                'contract_id' => 2,
                'name' => 'UpdateWrapRequest',
                'signature' => 'UpdateWrapRequest(hash,string)',
                'fingerprint' => 'd4bb11c0',
            ],
            8 => [
                'id' => 9,
                'contract_id' => 2,
                'name' => 'SetNetwork',
                'signature' => 'SetNetwork(uint32,uint32,string,string,string)',
                'fingerprint' => 'e4f0c639',
            ],
            9 => [
                'id' => 10,
                'contract_id' => 2,
                'name' => 'RemoveNetwork',
                'signature' => 'RemoveNetwork(uint32,uint32)',
                'fingerprint' => '3d36aac1',
            ],
            10 => [
                'id' => 11,
                'contract_id' => 2,
                'name' => 'SetTokenPair',
                'signature' => 'SetTokenPair(uint32,uint32,tokenStandard,string,bool,bool,bool,uint256,uint32,uint32,string)',
                'fingerprint' => 'd5292476',
            ],
            11 => [
                'id' => 12,
                'contract_id' => 2,
                'name' => 'SetNetworkMetadata',
                'signature' => 'SetNetworkMetadata(uint32,uint32,string)',
                'fingerprint' => 'ebea4402',
            ],
            12 => [
                'id' => 13,
                'contract_id' => 2,
                'name' => 'RemoveTokenPair',
                'signature' => 'RemoveTokenPair(uint32,uint32,tokenStandard,string)',
                'fingerprint' => 'b497bf39',
            ],
            13 => [
                'id' => 14,
                'contract_id' => 2,
                'name' => 'Halt',
                'signature' => 'Halt(string)',
                'fingerprint' => '72334d21',
            ],
            14 => [
                'id' => 15,
                'contract_id' => 2,
                'name' => 'Unhalt',
                'signature' => 'Unhalt()',
                'fingerprint' => '3a16f20e',
            ],
            15 => [
                'id' => 16,
                'contract_id' => 2,
                'name' => 'Emergency',
                'signature' => 'Emergency()',
                'fingerprint' => 'fa4ba15f',
            ],
            16 => [
                'id' => 17,
                'contract_id' => 2,
                'name' => 'ChangeTssECDSAPubKey',
                'signature' => 'ChangeTssECDSAPubKey(string,string,string)',
                'fingerprint' => '15a0c641',
            ],
            17 => [
                'id' => 18,
                'contract_id' => 2,
                'name' => 'ChangeAdministrator',
                'signature' => 'ChangeAdministrator(address)',
                'fingerprint' => '4f6bef7c',
            ],
            18 => [
                'id' => 19,
                'contract_id' => 2,
                'name' => 'ProposeAdministrator',
                'signature' => 'ProposeAdministrator(address)',
                'fingerprint' => '1ca313bd',
            ],
            19 => [
                'id' => 20,
                'contract_id' => 2,
                'name' => 'SetAllowKeyGen',
                'signature' => 'SetAllowKeyGen(bool)',
                'fingerprint' => '4b9b3ecb',
            ],
            20 => [
                'id' => 21,
                'contract_id' => 2,
                'name' => 'SetRedeemDelay',
                'signature' => 'SetRedeemDelay(uint64)',
                'fingerprint' => 'fd2411ec',
            ],
            21 => [
                'id' => 22,
                'contract_id' => 2,
                'name' => 'SetBridgeMetadata',
                'signature' => 'SetBridgeMetadata(string)',
                'fingerprint' => '96be29e3',
            ],
            22 => [
                'id' => 23,
                'contract_id' => 2,
                'name' => 'UnwrapToken',
                'signature' => 'UnwrapToken(uint32,uint32,hash,uint32,address,string,uint256,string)',
                'fingerprint' => 'b6069401',
            ],
            23 => [
                'id' => 24,
                'contract_id' => 2,
                'name' => 'RevokeUnwrapRequest',
                'signature' => 'RevokeUnwrapRequest(hash,uint32)',
                'fingerprint' => 'fa7c7f3d',
            ],
            24 => [
                'id' => 25,
                'contract_id' => 2,
                'name' => 'Redeem',
                'signature' => 'Redeem(hash,uint32)',
                'fingerprint' => 'd4e06c79',
            ],
            25 => [
                'id' => 26,
                'contract_id' => 2,
                'name' => 'NominateGuardians',
                'signature' => 'NominateGuardians(address[])',
                'fingerprint' => '688ac608',
            ],
            26 => [
                'id' => 27,
                'contract_id' => 2,
                'name' => 'SetOrchestratorInfo',
                'signature' => 'SetOrchestratorInfo(uint64,uint32,uint32,uint32)',
                'fingerprint' => 'eed69856',
            ],
            27 => [
                'id' => 28,
                'contract_id' => 3,
                'name' => 'DepositQsr',
                'signature' => 'DepositQsr()',
                'fingerprint' => 'd49577f4',
            ],
            28 => [
                'id' => 29,
                'contract_id' => 3,
                'name' => 'WithdrawQsr',
                'signature' => 'WithdrawQsr()',
                'fingerprint' => 'b3d658fd',
            ],
            29 => [
                'id' => 30,
                'contract_id' => 3,
                'name' => 'CollectReward',
                'signature' => 'CollectReward()',
                'fingerprint' => 'af43d3f0',
            ],
            30 => [
                'id' => 31,
                'contract_id' => 4,
                'name' => 'Create',
                'signature' => 'Create(address,int64,uint8,uint8,bytes)',
                'fingerprint' => '5c7e7110',
            ],
            31 => [
                'id' => 32,
                'contract_id' => 4,
                'name' => 'Reclaim',
                'signature' => 'Reclaim(hash)',
                'fingerprint' => '7e003c8d',
            ],
            32 => [
                'id' => 33,
                'contract_id' => 4,
                'name' => 'Unlock',
                'signature' => 'Unlock(hash,bytes)',
                'fingerprint' => 'd33791d3',
            ],
            33 => [
                'id' => 34,
                'contract_id' => 4,
                'name' => 'DenyProxyUnlock',
                'signature' => 'DenyProxyUnlock()',
                'fingerprint' => 'e17c39ed',
            ],
            34 => [
                'id' => 35,
                'contract_id' => 4,
                'name' => 'AllowProxyUnlock',
                'signature' => 'AllowProxyUnlock()',
                'fingerprint' => '57758f10',
            ],
            35 => [
                'id' => 36,
                'contract_id' => 5,
                'name' => 'Update',
                'signature' => 'Update()',
                'fingerprint' => '20093ea6',
            ],
            36 => [
                'id' => 37,
                'contract_id' => 5,
                'name' => 'Donate',
                'signature' => 'Donate()',
                'fingerprint' => 'cb7f8b2a',
            ],
            37 => [
                'id' => 38,
                'contract_id' => 5,
                'name' => 'Fund',
                'signature' => 'Fund(uint256,uint256)',
                'fingerprint' => '912f3c3f',
            ],
            38 => [
                'id' => 39,
                'contract_id' => 5,
                'name' => 'BurnZnn',
                'signature' => 'BurnZnn(uint256)',
                'fingerprint' => '096b75a4',
            ],
            39 => [
                'id' => 40,
                'contract_id' => 5,
                'name' => 'SetTokenTuple',
                'signature' => 'SetTokenTuple(string[],uint32[],uint32[],uint256[])',
                'fingerprint' => 'f0ad68db',
            ],
            40 => [
                'id' => 41,
                'contract_id' => 5,
                'name' => 'NominateGuardians',
                'signature' => 'NominateGuardians(address[])',
                'fingerprint' => '688ac608',
            ],
            41 => [
                'id' => 42,
                'contract_id' => 5,
                'name' => 'ProposeAdministrator',
                'signature' => 'ProposeAdministrator(address)',
                'fingerprint' => '1ca313bd',
            ],
            42 => [
                'id' => 43,
                'contract_id' => 5,
                'name' => 'Emergency',
                'signature' => 'Emergency()',
                'fingerprint' => 'fa4ba15f',
            ],
            43 => [
                'id' => 44,
                'contract_id' => 5,
                'name' => 'SetIsHalted',
                'signature' => 'SetIsHalted(bool)',
                'fingerprint' => '4649fe91',
            ],
            44 => [
                'id' => 45,
                'contract_id' => 5,
                'name' => 'LiquidityStake',
                'signature' => 'LiquidityStake(int64)',
                'fingerprint' => '071fa116',
            ],
            45 => [
                'id' => 46,
                'contract_id' => 5,
                'name' => 'CancelLiquidityStake',
                'signature' => 'CancelLiquidityStake(hash)',
                'fingerprint' => 'b8efc37c',
            ],
            46 => [
                'id' => 47,
                'contract_id' => 5,
                'name' => 'UnlockLiquidityStakeEntries',
                'signature' => 'UnlockLiquidityStakeEntries()',
                'fingerprint' => '616643ca',
            ],
            47 => [
                'id' => 48,
                'contract_id' => 5,
                'name' => 'SetAdditionalReward',
                'signature' => 'SetAdditionalReward(uint256,uint256)',
                'fingerprint' => 'a8fbfe56',
            ],
            48 => [
                'id' => 49,
                'contract_id' => 5,
                'name' => 'CollectReward',
                'signature' => 'CollectReward()',
                'fingerprint' => 'af43d3f0',
            ],
            49 => [
                'id' => 50,
                'contract_id' => 5,
                'name' => 'ChangeAdministrator',
                'signature' => 'ChangeAdministrator(address)',
                'fingerprint' => '4f6bef7c',
            ],
            50 => [
                'id' => 51,
                'contract_id' => 6,
                'name' => 'Register',
                'signature' => 'Register(string,address,address,uint8,uint8)',
                'fingerprint' => '644de927',
            ],
            51 => [
                'id' => 52,
                'contract_id' => 6,
                'name' => 'RegisterLegacy',
                'signature' => 'RegisterLegacy(string,address,address,uint8,uint8,string,string)',
                'fingerprint' => 'e4588207',
            ],
            52 => [
                'id' => 53,
                'contract_id' => 6,
                'name' => 'Revoke',
                'signature' => 'Revoke(string)',
                'fingerprint' => '95631306',
            ],
            53 => [
                'id' => 54,
                'contract_id' => 6,
                'name' => 'UpdatePillar',
                'signature' => 'UpdatePillar(string,address,address,uint8,uint8)',
                'fingerprint' => 'de0ae34b',
            ],
            54 => [
                'id' => 55,
                'contract_id' => 6,
                'name' => 'Delegate',
                'signature' => 'Delegate(string)',
                'fingerprint' => '7c2d5d6e',
            ],
            55 => [
                'id' => 56,
                'contract_id' => 6,
                'name' => 'Undelegate',
                'signature' => 'Undelegate()',
                'fingerprint' => '7e8952c8',
            ],
            56 => [
                'id' => 57,
                'contract_id' => 7,
                'name' => 'Fuse',
                'signature' => 'Fuse(address)',
                'fingerprint' => '5ac942e8',
            ],
            57 => [
                'id' => 58,
                'contract_id' => 7,
                'name' => 'CancelFuse',
                'signature' => 'CancelFuse(hash)',
                'fingerprint' => 'f9ca9dc3',
            ],
            58 => [
                'id' => 59,
                'contract_id' => 8,
                'name' => 'Register',
                'signature' => 'Register()',
                'fingerprint' => '4dd23517',
            ],
            59 => [
                'id' => 60,
                'contract_id' => 8,
                'name' => 'Revoke',
                'signature' => 'Revoke()',
                'fingerprint' => '58363e24',
            ],
            60 => [
                'id' => 61,
                'contract_id' => 9,
                'name' => 'Stake',
                'signature' => 'Stake(int64)',
                'fingerprint' => 'd802845a',
            ],
            61 => [
                'id' => 62,
                'contract_id' => 9,
                'name' => 'Cancel',
                'signature' => 'Cancel(hash)',
                'fingerprint' => '5a92fe32',
            ],
            62 => [
                'id' => 63,
                'contract_id' => 10,
                'name' => 'RetrieveAssets',
                'signature' => 'RetrieveAssets(string,string)',
                'fingerprint' => '47f12c81',
            ],
            63 => [
                'id' => 64,
                'contract_id' => 11,
                'name' => 'IssueToken',
                'signature' => 'IssueToken(string,string,string,uint256,uint256,uint8,bool,bool,bool)',
                'fingerprint' => 'bc410b91',
            ],
            64 => [
                'id' => 65,
                'contract_id' => 11,
                'name' => 'Mint',
                'signature' => 'Mint(tokenStandard,uint256,address)',
                'fingerprint' => 'cd70f9bc',
            ],
            65 => [
                'id' => 66,
                'contract_id' => 11,
                'name' => 'Burn',
                'signature' => 'Burn()',
                'fingerprint' => '3395ab94',
            ],
            66 => [
                'id' => 67,
                'contract_id' => 11,
                'name' => 'UpdateToken',
                'signature' => 'UpdateToken(tokenStandard,address,bool,bool)',
                'fingerprint' => '2a3cf32c',
            ],
        ]);
    }
}
